name: alquran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  http: 0.13.4
  change_app_package_name: 1.0.0
  google_fonts: 2.3.1
  flutter_svg: 1.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/illustrations/
    - assets/icons/
  uses-material-design: true

